### PR TITLE
Let list state benchmark stable

### PR DESCRIPTION
**Pull request by klion26**
Make two changes to let the benchmark stable.
1. Add a call of `RocksDBKeyedStateBackend.compactState` at end of `tearDownPerIteration`, to make sure the drained elements are physically deleted.
2. Add a call of `RocksDBKeyedStateBackend.compactStat`e at end of `setUpPerIteration`, to make sure only one sst file left, so all get invocation will access this single file, to prevent the spike caused by different key distribution in multiple sst files (the more access to the older sst file, the lower throughput will be).

### CODE REVIEW

**Review by carp84 — APPROVED** [review]
Thanks for the patch @klion26 , changes LGTM. Could you post the benchmark result with this fix so we could get an intuitive view about how the deviation looks like now? Thanks.

**Comment by klion26** [comment]
thanks for the review @carp84 , I attached all the result of list state bench below

final result
```
# Run complete. Total time: 00:42:24

Benchmark                             (backendType)   Mode  Cnt     Score     Error   Units
ListStateBenchmark.listAdd                     HEAP  thrpt   30  4622.639 ± 231.511  ops/ms
ListStateBenchmark.listAdd                  ROCKSDB  thrpt   30   483.143 ±   2.736  ops/ms
ListStateBenchmark.listAddAll                  HEAP  thrpt   30   625.105 ±  19.140  ops/ms
ListStateBenchmark.listAddAll               ROCKSDB  thrpt   30   269.526 ±   1.238  ops/ms
ListStateBenchmark.listGet                     HEAP  thrpt   30  2478.560 ±  15.640  ops/ms
ListStateBenchmark.listGet                  ROCKSDB  thrpt   30   143.864 ±   0.531  ops/ms
ListStateBenchmark.listGetAndIterate           HEAP  thrpt   30  2408.530 ±  11.669  ops/ms
ListStateBenchmark.listGetAndIterate        ROCKSDB  thrpt   30   143.046 ±   1.181  ops/ms
ListStateBenchmark.listUpdate                  HEAP  thrpt   30  2510.793 ±  12.819  ops/ms
ListStateBenchmark.listUpdate               ROCKSDB  thrpt   30   471.911 ±  11.300  ops/ms
```

detail data
```
# Benchmark: org.apache.flink.state.benchmark.ListStateBenchmark.listAdd
# Parameters: (backendType = HEAP)

# Run progress: 0.00% complete, ETA 00:10:00
# Fork: 1 of 3
# Warmup Iteration   1: 2747.118 ops/ms
# Warmup Iteration   2: 3952.418 ops/ms
# Warmup Iteration   3: 4138.142 ops/ms
# Warmup Iteration   4: 4095.218 ops/ms
# Warmup Iteration   5: 4239.088 ops/ms
# Warmup Iteration   6: 4062.985 ops/ms
# Warmup Iteration   7: 4214.623 ops/ms
# Warmup Iteration   8: 4186.120 ops/ms
# Warmup Iteration   9: 4253.048 ops/ms
# Warmup Iteration  10: 4088.097 ops/ms
Iteration   1: 4153.446 ops/ms
Iteration   2: 4146.259 ops/ms
Iteration   3: 4313.822 ops/ms
Iteration   4: 4102.385 ops/ms
Iteration   5: 4194.433 ops/ms
Iteration   6: 4128.753 ops/ms
Iteration   7: 4177.137 ops/ms
Iteration   8: 4081.026 ops/ms
Iteration   9: 4135.877 ops/ms
Iteration  10: 4178.879 ops/ms
# Run progress: 3.33% complete, ETA 00:27:15
# Fork: 2 of 3
# Warmup Iteration   1: 3081.049 ops/ms
# Warmup Iteration   2: 3925.284 ops/ms
# Warmup Iteration   3: 4872.042 ops/ms
# Warmup Iteration   4: 5028.556 ops/ms
# Warmup Iteration   5: 5167.872 ops/ms
# Warmup Iteration   6: 5061.633 ops/ms
# Warmup Iteration   7: 5107.947 ops/ms
# Warmup Iteration   8: 4928.044 ops/ms
# Warmup Iteration   9: 5039.320 ops/ms
# Warmup Iteration  10: 4884.636 ops/ms
Iteration   1: 4873.695 ops/ms
Iteration   2: 4899.583 ops/ms
Iteration   3: 4938.004 ops/ms
Iteration   4: 4879.485 ops/ms
Iteration   5: 5015.646 ops/ms
Iteration   6: 4956.239 ops/ms
Iteration   7: 4994.387 ops/ms
Iteration   8: 4971.696 ops/ms
Iteration   9: 4949.882 ops/ms
Iteration  10: 4904.694 ops/ms

# Run progress: 6.67% complete, ETA 00:26:17
# Fork: 3 of 3
# Warmup Iteration   1: 2885.327 ops/ms
# Warmup Iteration   2: 4211.079 ops/ms
# Warmup Iteration   3: 4756.917 ops/ms
# Warmup Iteration   4: 4628.147 ops/ms
# Warmup Iteration   5: 4754.001 ops/ms
# Warmup Iteration   6: 4765.895 ops/ms
# Warmup Iteration   7: 4835.759 ops/ms
# Warmup Iteration   8: 4881.359 ops/ms
# Warmup Iteration   9: 4888.253 ops/ms
# Warmup Iteration  10: 4848.409 ops/ms
Iteration   1: 4731.417 ops/ms
Iteration   2: 4882.209 ops/ms
Iteration   3: 4840.425 ops/ms
Iteration   4: 4771.422 ops/ms
Iteration   5: 4792.707 ops/ms
Iteration   6: 4515.525 ops/ms
Iteration   7: 4793.248 ops/ms
Iteration   8: 4777.885 ops/ms
Iteration   9: 4803.420 ops/ms
Iteration  10: 4775.579 ops/ms

# Benchmark: org.apache.flink.state.benchmark.ListStateBenchmark.listAdd
# Parameters: (backendType = ROCKSDB)

# Run progress: 10.00% complete, ETA 00:25:20
# Fork: 1 of 3
# Warmup Iteration   1: 474.681 ops/ms
# Warmup Iteration   2: 485.956 ops/ms
# Warmup Iteration   3: 490.588 ops/ms
# Warmup Iteration   4: 487.987 ops/ms
# Warmup Iteration   5: 488.868 ops/ms
# Warmup Iteration   6: 479.972 ops/ms
# Warmup Iteration   7: 478.789 ops/ms
# Warmup Iteration   8: 483.100 ops/ms
# Warmup Iteration   9: 489.760 ops/ms
# Warmup Iteration  10: 480.961 ops/ms
Iteration   1: 483.947 ops/ms
Iteration   2: 485.917 ops/ms
Iteration   3: 484.958 ops/ms
Iteration   4: 486.110 ops/ms
Iteration   5: 483.319 ops/ms
Iteration   6: 489.953 ops/ms
Iteration   7: 480.888 ops/ms
Iteration   8: 485.107 ops/ms
Iteration   9: 489.039 ops/ms
Iteration  10: 483.991 ops/ms
# Run progress: 13.33% complete, ETA 00:32:19
# Fork: 2 of 3
# Warmup Iteration   1: 463.975 ops/ms
# Warmup Iteration   2: 482.668 ops/ms
# Warmup Iteration   3: 478.978 ops/ms
# Warmup Iteration   4: 479.089 ops/ms
# Warmup Iteration   5: 481.786 ops/ms
# Warmup Iteration   6: 478.043 ops/ms
# Warmup Iteration   7: 477.525 ops/ms
# Warmup Iteration   8: 490.386 ops/ms
# Warmup Iteration   9: 482.265 ops/ms
# Warmup Iteration  10: 489.308 ops/ms
Iteration   1: 475.864 ops/ms
Iteration   2: 485.130 ops/ms
Iteration   3: 474.836 ops/ms
Iteration   4: 482.300 ops/ms
Iteration   5: 482.308 ops/ms
Iteration   6: 481.828 ops/ms
Iteration   7: 480.635 ops/ms
Iteration   8: 477.770 ops/ms
Iteration   9: 480.701 ops/ms
Iteration  10: 483.509 ops/ms
# Run progress: 16.67% complete, ETA 00:35:49
# Fork: 3 of 3
# Warmup Iteration   1: 476.115 ops/ms
# Warmup Iteration   2: 477.144 ops/ms
# Warmup Iteration   3: 483.874 ops/ms
# Warmup Iteration   4: 484.937 ops/ms
# Warmup Iteration   5: 484.351 ops/ms
# Warmup Iteration   6: 486.171 ops/ms
# Warmup Iteration   7: 489.699 ops/ms
# Warmup Iteration   8: 472.979 ops/ms
# Warmup Iteration   9: 481.117 ops/ms
# Warmup Iteration  10: 490.032 ops/ms
Iteration   1: 483.812 ops/ms
Iteration   2: 481.397 ops/ms
Iteration   3: 486.232 ops/ms
Iteration   4: 484.644 ops/ms
Iteration   5: 475.515 ops/ms
Iteration   6: 490.804 ops/ms
Iteration   7: 488.860 ops/ms
Iteration   8: 486.307 ops/ms
Iteration   9: 478.903 ops/ms
Iteration  10: 479.697 ops/ms

# Benchmark: org.apache.flink.state.benchmark.ListStateBenchmark.listAddAll
# Parameters: (backendType = HEAP)

# Run progress: 20.00% complete, ETA 00:37:26
# Fork: 1 of 3
# Warmup Iteration   1: 194.615 ops/ms
# Warmup Iteration   2: 626.889 ops/ms
# Warmup Iteration   3: 621.644 ops/ms
# Warmup Iteration   4: 630.543 ops/ms
# Warmup Iteration   5: 623.744 ops/ms
# Warmup Iteration   6: 625.691 ops/ms
# Warmup Iteration   7: 626.457 ops/ms
# Warmup Iteration   8: 631.180 ops/ms
# Warmup Iteration   9: 633.097 ops/ms
# Warmup Iteration  10: 625.819 ops/ms
Iteration   1: 733.848 ops/ms
Iteration   2: 629.047 ops/ms
Iteration   3: 632.935 ops/ms
Iteration   4: 627.718 ops/ms
Iteration   5: 627.368 ops/ms
Iteration   6: 629.003 ops/ms
Iteration   7: 630.493 ops/ms
Iteration   8: 628.135 ops/ms
Iteration   9: 623.835 ops/ms
Iteration  10: 627.792 ops/ms

# Run progress: 23.33% complete, ETA 00:33:34
# Fork: 2 of 3
# Warmup Iteration   1: 196.995 ops/ms
# Warmup Iteration   2: 607.069 ops/ms
# Warmup Iteration   3: 614.593 ops/ms
# Warmup Iteration   4: 623.000 ops/ms
# Warmup Iteration   5: 612.782 ops/ms
# Warmup Iteration   6: 615.784 ops/ms
# Warmup Iteration   7: 617.146 ops/ms
# Warmup Iteration   8: 613.731 ops/ms
# Warmup Iteration   9: 611.914 ops/ms
# Warmup Iteration  10: 616.760 ops/ms
Iteration   1: 614.008 ops/ms
Iteration   2: 614.896 ops/ms
Iteration   3: 616.812 ops/ms
Iteration   4: 614.159 ops/ms
Iteration   5: 613.498 ops/ms
Iteration   6: 616.537 ops/ms
Iteration   7: 615.112 ops/ms
Iteration   8: 605.044 ops/ms
Iteration   9: 613.347 ops/ms
Iteration  10: 610.808 ops/ms
# Run progress: 26.67% complete, ETA 00:30:27
# Fork: 3 of 3
# Warmup Iteration   1: 207.642 ops/ms
# Warmup Iteration   2: 602.392 ops/ms
# Warmup Iteration   3: 612.841 ops/ms
# Warmup Iteration   4: 613.793 ops/ms
# Warmup Iteration   5: 613.034 ops/ms
# Warmup Iteration   6: 611.978 ops/ms
# Warmup Iteration   7: 610.555 ops/ms
# Warmup Iteration   8: 610.418 ops/ms
# Warmup Iteration   9: 608.982 ops/ms
# Warmup Iteration  10: 612.480 ops/ms
Iteration   1: 613.878 ops/ms
Iteration   2: 619.546 ops/ms
Iteration   3: 611.912 ops/ms
Iteration   4: 607.181 ops/ms
Iteration   5: 613.152 ops/ms
Iteration   6: 612.305 ops/ms
Iteration   7: 610.589 ops/ms
Iteration   8: 718.756 ops/ms
Iteration   9: 610.935 ops/ms
Iteration  10: 610.509 ops/ms

# Benchmark: org.apache.flink.state.benchmark.ListStateBenchmark.listAddAll
# Parameters: (backendType = ROCKSDB)

# Run progress: 30.00% complete, ETA 00:27:50
# Fork: 1 of 3
# Warmup Iteration   1: 189.885 ops/ms
# Warmup Iteration   2: 218.039 ops/ms
# Warmup Iteration   3: 269.548 ops/ms
# Warmup Iteration   4: 270.008 ops/ms
# Warmup Iteration   5: 269.473 ops/ms
# Warmup Iteration   6: 259.877 ops/ms
# Warmup Iteration   7: 264.667 ops/ms
# Warmup Iteration   8: 268.274 ops/ms
# Warmup Iteration   9: 268.141 ops/ms
# Warmup Iteration  10: 267.456 ops/ms
Iteration   1: 269.072 ops/ms
Iteration   2: 267.844 ops/ms
Iteration   3: 269.670 ops/ms
Iteration   4: 263.701 ops/ms
Iteration   5: 266.301 ops/ms
Iteration   6: 268.088 ops/ms
Iteration   7: 267.881 ops/ms
Iteration   8: 266.889 ops/ms
Iteration   9: 267.550 ops/ms
Iteration  10: 268.233 ops/ms

# Warmup Iteration   1: 231.002 ops/ms
# Warmup Iteration   2: 258.994 ops/ms
# Warmup Iteration   3: 270.857 ops/ms
# Warmup Iteration   4: 271.477 ops/ms
# Warmup Iteration   5: 271.411 ops/ms
# Warmup Iteration   6: 272.212 ops/ms
# Warmup Iteration   7: 271.356 ops/ms
# Warmup Iteration   8: 263.457 ops/ms
# Warmup Iteration   9: 270.446 ops/ms
# Warmup Iteration  10: 270.580 ops/ms
Iteration   1: 271.644 ops/ms
Iteration   2: 270.941 ops/ms
Iteration   3: 269.671 ops/ms
Iteration   4: 269.080 ops/ms
Iteration   5: 269.901 ops/ms
Iteration   6: 271.536 ops/ms
Iteration   7: 271.027 ops/ms
Iteration   8: 270.385 ops/ms
Iteration   9: 269.791 ops/ms
Iteration  10: 270.393 ops/ms

# Run progress: 36.67% complete, ETA 00:27:26
# Fork: 3 of 3
# Warmup Iteration   1: 232.124 ops/ms
# Warmup Iteration   2: 258.335 ops/ms
# Warmup Iteration   3: 272.337 ops/ms
# Warmup Iteration   4: 271.519 ops/ms
# Warmup Iteration   5: 270.012 ops/ms
# Warmup Iteration   6: 270.898 ops/ms
# Warmup Iteration   7: 270.051 ops/ms
# Warmup Iteration   8: 270.853 ops/ms
# Warmup Iteration   9: 271.336 ops/ms
# Warmup Iteration  10: 271.238 ops/ms
Iteration   1: 271.397 ops/ms
Iteration   2: 271.248 ops/ms
Iteration   3: 271.360 ops/ms
Iteration   4: 270.417 ops/ms
Iteration   5: 271.066 ops/ms
Iteration   6: 272.103 ops/ms
Iteration   7: 269.010 ops/ms
Iteration   8: 269.735 ops/ms
Iteration   9: 269.945 ops/ms
Iteration  10: 269.887 ops/ms

# Benchmark: org.apache.flink.state.benchmark.ListStateBenchmark.listGet
# Parameters: (backendType = HEAP)

# Run progress: 40.00% complete, ETA 00:26:44
# Fork: 1 of 3
# Warmup Iteration   1: 2277.742 ops/ms
# Warmup Iteration   2: 2438.685 ops/ms
# Warmup Iteration   3: 2504.570 ops/ms
# Warmup Iteration   4: 2506.975 ops/ms
# Warmup Iteration   5: 2476.924 ops/ms
# Warmup Iteration   6: 2512.746 ops/ms
# Warmup Iteration   7: 2510.767 ops/ms
# Warmup Iteration   8: 2506.774 ops/ms
# Warmup Iteration   9: 2496.482 ops/ms
# Warmup Iteration  10: 2511.580 ops/ms
Iteration   1: 2513.477 ops/ms
Iteration   2: 2509.943 ops/ms
Iteration   3: 2509.819 ops/ms
Iteration   4: 2512.211 ops/ms
Iteration   5: 2498.990 ops/ms
Iteration   6: 2484.976 ops/ms
Iteration   7: 2497.178 ops/ms
Iteration   8: 2455.686 ops/ms
Iteration   9: 2491.208 ops/ms
Iteration  10: 2491.761 ops/ms

# Run progress: 43.33% complete, ETA 00:24:27
# Fork: 2 of 3
# Warmup Iteration   1: 2302.155 ops/ms
# Warmup Iteration   2: 2328.257 ops/ms
# Warmup Iteration   3: 2469.602 ops/ms
# Warmup Iteration   4: 2459.318 ops/ms
# Warmup Iteration   5: 2470.244 ops/ms
# Warmup Iteration   6: 2466.831 ops/ms
# Warmup Iteration   7: 2470.892 ops/ms
# Warmup Iteration   8: 2467.100 ops/ms
# Warmup Iteration   9: 2474.856 ops/ms
# Warmup Iteration  10: 2470.950 ops/ms
Iteration   1: 2472.805 ops/ms
Iteration   2: 2456.083 ops/ms
Iteration   3: 2459.563 ops/ms
Iteration   4: 2474.806 ops/ms
Iteration   5: 2471.559 ops/ms
Iteration   6: 2444.132 ops/ms
Iteration   7: 2409.615 ops/ms
Iteration   8: 2449.876 ops/ms
Iteration   9: 2445.541 ops/ms
Iteration  10: 2455.189 ops/ms

# Run progress: 46.67% complete, ETA 00:22:22
# Fork: 3 of 3
# Warmup Iteration   1: 2302.892 ops/ms
# Warmup Iteration   2: 2443.095 ops/ms
# Warmup Iteration   3: 2484.587 ops/ms
# Warmup Iteration   4: 2487.990 ops/ms
# Warmup Iteration   5: 2489.694 ops/ms
# Warmup Iteration   6: 2491.424 ops/ms
# Warmup Iteration   7: 2492.486 ops/ms
# Warmup Iteration   8: 2488.246 ops/ms
# Warmup Iteration   9: 2478.889 ops/ms
# Warmup Iteration  10: 2473.638 ops/ms
Iteration   1: 2489.718 ops/ms
Iteration   2: 2485.066 ops/ms
Iteration   3: 2488.578 ops/ms
Iteration   4: 2488.551 ops/ms
Iteration   5: 2478.895 ops/ms
Iteration   6: 2486.684 ops/ms
Iteration   7: 2484.063 ops/ms
Iteration   8: 2486.794 ops/ms
Iteration   9: 2481.472 ops/ms
Iteration  10: 2482.550 ops/ms

# Benchmark: org.apache.flink.state.benchmark.ListStateBenchmark.listGet
# Parameters: (backendType = ROCKSDB)

# Run progress: 50.00% complete, ETA 00:20:27
# Fork: 1 of 3
# Warmup Iteration   1: 123.618 ops/ms
# Warmup Iteration   2: 144.643 ops/ms
# Warmup Iteration   3: 144.007 ops/ms
# Warmup Iteration   4: 144.020 ops/ms
# Warmup Iteration   5: 144.770 ops/ms
# Warmup Iteration   6: 144.947 ops/ms
# Warmup Iteration   7: 144.425 ops/ms
# Warmup Iteration   8: 144.676 ops/ms
# Warmup Iteration   9: 144.577 ops/ms
# Warmup Iteration  10: 145.656 ops/ms
Iteration   1: 144.003 ops/ms
Iteration   2: 144.051 ops/ms
Iteration   3: 145.563 ops/ms
Iteration   4: 143.415 ops/ms
Iteration   5: 143.331 ops/ms
Iteration   6: 144.214 ops/ms
Iteration   7: 146.075 ops/ms
Iteration   8: 144.420 ops/ms
Iteration   9: 144.571 ops/ms
Iteration  10: 145.174 ops/ms

# Fork: 2 of 3
# Warmup Iteration   1: 121.247 ops/ms
# Warmup Iteration   2: 142.595 ops/ms
# Warmup Iteration   3: 143.108 ops/ms
# Warmup Iteration   4: 143.613 ops/ms
# Warmup Iteration   5: 143.433 ops/ms
# Warmup Iteration   6: 143.354 ops/ms
# Warmup Iteration   7: 143.568 ops/ms
# Warmup Iteration   8: 142.871 ops/ms
# Warmup Iteration   9: 143.287 ops/ms
# Warmup Iteration  10: 142.672 ops/ms
Iteration   1: 143.565 ops/ms
Iteration   2: 143.515 ops/ms
Iteration   3: 142.822 ops/ms
Iteration   4: 142.579 ops/ms
Iteration   5: 143.406 ops/ms
Iteration   6: 143.316 ops/ms
Iteration   7: 142.985 ops/ms
Iteration   8: 143.346 ops/ms
Iteration   9: 142.942 ops/ms
Iteration  10: 143.281 ops/ms

# Fork: 3 of 3
# Warmup Iteration   1: 123.480 ops/ms
# Warmup Iteration   2: 143.719 ops/ms
# Warmup Iteration   3: 143.852 ops/ms
# Warmup Iteration   4: 142.160 ops/ms
# Warmup Iteration   5: 143.914 ops/ms
# Warmup Iteration   6: 144.197 ops/ms
# Warmup Iteration   7: 141.737 ops/ms
# Warmup Iteration   8: 144.188 ops/ms
# Warmup Iteration   9: 142.753 ops/ms
# Warmup Iteration  10: 143.853 ops/ms
Iteration   1: 144.052 ops/ms
Iteration   2: 143.870 ops/ms
Iteration   3: 143.560 ops/ms
Iteration   4: 144.369 ops/ms
Iteration   5: 143.859 ops/ms
Iteration   6: 143.959 ops/ms
Iteration   7: 143.980 ops/ms
Iteration   8: 144.173 ops/ms
Iteration   9: 144.522 ops/ms
Iteration  10: 143.019 ops/ms

# Benchmark: org.apache.flink.state.benchmark.ListStateBenchmark.listGetAndIterate
# Parameters: (backendType = HEAP)

# Run progress: 60.00% complete, ETA 00:17:12
# Fork: 1 of 3
# Warmup Iteration   1: 2222.168 ops/ms
# Warmup Iteration   2: 2354.881 ops/ms
# Warmup Iteration   3: 2378.811 ops/ms
# Warmup Iteration   4: 2434.522 ops/ms
# Warmup Iteration   5: 2421.853 ops/ms
# Warmup Iteration   6: 2412.098 ops/ms
# Warmup Iteration   7: 2431.324 ops/ms
# Warmup Iteration   8: 2428.732 ops/ms
# Warmup Iteration   9: 2420.553 ops/ms
# Warmup Iteration  10: 2432.907 ops/ms
Iteration   1: 2409.649 ops/ms
Iteration   2: 2425.501 ops/ms
Iteration   3: 2410.121 ops/ms
Iteration   4: 2375.570 ops/ms
Iteration   5: 2406.289 ops/ms
Iteration   6: 2365.513 ops/ms
Iteration   7: 2415.350 ops/ms
Iteration   8: 2379.082 ops/ms
Iteration   9: 2410.733 ops/ms
Iteration  10: 2401.812 ops/ms

# Fork: 2 of 3
# Warmup Iteration   1: 2232.201 ops/ms
# Warmup Iteration   2: 2383.957 ops/ms
# Warmup Iteration   3: 2425.586 ops/ms
# Warmup Iteration   4: 2421.829 ops/ms
# Warmup Iteration   5: 2431.614 ops/ms
# Warmup Iteration   6: 2428.120 ops/ms
# Warmup Iteration   7: 2430.496 ops/ms
# Warmup Iteration   8: 2431.601 ops/ms
# Warmup Iteration   9: 2426.134 ops/ms
# Warmup Iteration  10: 2431.856 ops/ms
Iteration   1: 2427.665 ops/ms
Iteration   2: 2422.996 ops/ms
Iteration   3: 2366.553 ops/ms
Iteration   4: 2417.445 ops/ms
Iteration   5: 2424.920 ops/ms
Iteration   6: 2410.773 ops/ms
Iteration   7: 2411.028 ops/ms
Iteration   8: 2419.382 ops/ms
Iteration   9: 2422.019 ops/ms
Iteration  10: 2409.152 ops/ms

# Fork: 3 of 3
# Warmup Iteration   1: 2249.749 ops/ms
# Warmup Iteration   2: 2356.798 ops/ms
# Warmup Iteration   3: 2366.033 ops/ms
# Warmup Iteration   4: 2394.996 ops/ms
# Warmup Iteration   5: 2415.035 ops/ms
# Warmup Iteration   6: 2398.589 ops/ms
# Warmup Iteration   7: 2415.815 ops/ms
# Warmup Iteration   8: 2406.318 ops/ms
# Warmup Iteration   9: 2416.378 ops/ms
# Warmup Iteration  10: 2417.659 ops/ms
Iteration   1: 2421.131 ops/ms
Iteration   2: 2416.693 ops/ms
Iteration   3: 2423.462 ops/ms
Iteration   4: 2389.433 ops/ms
Iteration   5: 2419.784 ops/ms
Iteration   6: 2433.883 ops/ms
Iteration   7: 2408.668 ops/ms
Iteration   8: 2402.676 ops/ms
Iteration   9: 2404.628 ops/ms
Iteration  10: 2404.005 ops/ms

# Benchmark: org.apache.flink.state.benchmark.ListStateBenchmark.listGetAndIterate
# Parameters: (backendType = ROCKSDB)

# Run progress: 70.00% complete, ETA 00:12:11
# Fork: 1 of 3
# Warmup Iteration   1: 123.388 ops/ms
# Warmup Iteration   2: 145.034 ops/ms
# Warmup Iteration   3: 144.339 ops/ms
# Warmup Iteration   4: 145.721 ops/ms
# Warmup Iteration   5: 145.407 ops/ms
# Warmup Iteration   6: 143.832 ops/ms
# Warmup Iteration   7: 144.952 ops/ms
# Warmup Iteration   8: 145.184 ops/ms
# Warmup Iteration   9: 145.804 ops/ms
# Warmup Iteration  10: 143.894 ops/ms
Iteration   1: 143.893 ops/ms
Iteration   2: 144.199 ops/ms
Iteration   3: 144.977 ops/ms
Iteration   4: 144.362 ops/ms
Iteration   5: 145.709 ops/ms
Iteration   6: 145.932 ops/ms
Iteration   7: 144.602 ops/ms
Iteration   8: 145.109 ops/ms
Iteration   9: 146.241 ops/ms
Iteration  10: 145.805 ops/ms

# Fork: 2 of 3
# Warmup Iteration   1: 123.446 ops/ms
# Warmup Iteration   2: 143.415 ops/ms
# Warmup Iteration   3: 143.080 ops/ms
# Warmup Iteration   4: 143.132 ops/ms
# Warmup Iteration   5: 142.955 ops/ms
# Warmup Iteration   6: 143.125 ops/ms
# Warmup Iteration   7: 143.550 ops/ms
# Warmup Iteration   8: 142.472 ops/ms
# Warmup Iteration   9: 142.050 ops/ms
# Warmup Iteration  10: 141.857 ops/ms
Iteration   1: 142.976 ops/ms
Iteration   2: 142.026 ops/ms
Iteration   3: 142.238 ops/ms
Iteration   4: 143.129 ops/ms
Iteration   5: 142.186 ops/ms
Iteration   6: 142.893 ops/ms
Iteration   7: 143.456 ops/ms
Iteration   8: 144.078 ops/ms
Iteration   9: 143.102 ops/ms
Iteration  10: 143.426 ops/ms

# Fork: 3 of 3
# Warmup Iteration   1: 121.530 ops/ms
# Warmup Iteration   2: 142.272 ops/ms
# Warmup Iteration   3: 140.903 ops/ms
# Warmup Iteration   4: 141.341 ops/ms
# Warmup Iteration   5: 140.449 ops/ms
# Warmup Iteration   6: 141.566 ops/ms
# Warmup Iteration   7: 141.458 ops/ms
# Warmup Iteration   8: 141.448 ops/ms
# Warmup Iteration   9: 140.855 ops/ms
# Warmup Iteration  10: 141.602 ops/ms
Iteration   1: 141.379 ops/ms
Iteration   2: 141.095 ops/ms
Iteration   3: 140.346 ops/ms
Iteration   4: 141.556 ops/ms
Iteration   5: 141.484 ops/ms
Iteration   6: 140.502 ops/ms
Iteration   7: 141.449 ops/ms
Iteration   8: 140.832 ops/ms
Iteration   9: 141.387 ops/ms
Iteration  10: 141.009 ops/ms

# Benchmark: org.apache.flink.state.benchmark.ListStateBenchmark.listUpdate
# Parameters: (backendType = HEAP)

# Run progress: 80.00% complete, ETA 00:08:26
# Fork: 1 of 3
# Warmup Iteration   1: 1975.456 ops/ms
# Warmup Iteration   2: 2478.174 ops/ms
# Warmup Iteration   3: 2524.177 ops/ms
# Warmup Iteration   4: 2519.622 ops/ms
# Warmup Iteration   5: 2509.564 ops/ms
# Warmup Iteration   6: 2512.860 ops/ms
# Warmup Iteration   7: 2543.957 ops/ms
# Warmup Iteration   8: 2539.232 ops/ms
# Warmup Iteration   9: 2543.424 ops/ms
# Warmup Iteration  10: 2527.953 ops/ms
Iteration   1: 2470.271 ops/ms
Iteration   2: 2520.844 ops/ms
Iteration   3: 2515.336 ops/ms
Iteration   4: 2526.794 ops/ms
Iteration   5: 2496.039 ops/ms
Iteration   6: 2538.024 ops/ms
Iteration   7: 2523.637 ops/ms
Iteration   8: 2525.009 ops/ms
Iteration   9: 2535.830 ops/ms
Iteration  10: 2504.703 ops/ms

# Fork: 2 of 3
# Warmup Iteration   1: 2030.848 ops/ms
# Warmup Iteration   2: 2450.552 ops/ms
# Warmup Iteration   3: 2517.156 ops/ms
# Warmup Iteration   4: 2516.432 ops/ms
# Warmup Iteration   5: 2524.702 ops/ms
# Warmup Iteration   6: 2531.280 ops/ms
# Warmup Iteration   7: 2509.534 ops/ms
# Warmup Iteration   8: 2500.757 ops/ms
# Warmup Iteration   9: 2505.926 ops/ms
# Warmup Iteration  10: 2414.784 ops/ms
Iteration   1: 2523.041 ops/ms
Iteration   2: 2486.104 ops/ms
Iteration   3: 2511.753 ops/ms
Iteration   4: 2472.975 ops/ms
Iteration   5: 2512.058 ops/ms
Iteration   6: 2512.286 ops/ms
Iteration   7: 2519.653 ops/ms
Iteration   8: 2500.491 ops/ms
Iteration   9: 2502.351 ops/ms
Iteration  10: 2521.916 ops/ms

# Fork: 3 of 3
# Warmup Iteration   1: 2046.828 ops/ms
# Warmup Iteration   2: 2500.752 ops/ms
# Warmup Iteration   3: 2520.470 ops/ms
# Warmup Iteration   4: 2517.790 ops/ms
# Warmup Iteration   5: 2529.368 ops/ms
# Warmup Iteration   6: 2523.913 ops/ms
# Warmup Iteration   7: 2538.117 ops/ms
# Warmup Iteration   8: 2513.699 ops/ms
# Warmup Iteration   9: 2467.203 ops/ms
# Warmup Iteration  10: 2512.432 ops/ms
Iteration   1: 2469.801 ops/ms
Iteration   2: 2516.627 ops/ms
Iteration   3: 2481.876 ops/ms
Iteration   4: 2512.943 ops/ms
Iteration   5: 2526.525 ops/ms
Iteration   6: 2539.952 ops/ms
Iteration   7: 2528.862 ops/ms
Iteration   8: 2517.614 ops/ms
Iteration   9: 2503.919 ops/ms
Iteration  10: 2506.553 ops/ms

# Benchmark: org.apache.flink.state.benchmark.ListStateBenchmark.listUpdate
# Parameters: (backendType = ROCKSDB)

# Run progress: 90.00% complete, ETA 00:04:02
# Fork: 1 of 3
# Warmup Iteration   1: 469.550 ops/ms
# Warmup Iteration   2: 478.394 ops/ms
# Warmup Iteration   3: 478.060 ops/ms
# Warmup Iteration   4: 483.975 ops/ms
# Warmup Iteration   5: 474.441 ops/ms
# Warmup Iteration   6: 471.146 ops/ms
# Warmup Iteration   7: 481.750 ops/ms
# Warmup Iteration   8: 486.313 ops/ms
# Warmup Iteration   9: 483.874 ops/ms
# Warmup Iteration  10: 476.982 ops/ms
Iteration   1: 488.848 ops/ms
Iteration   2: 476.528 ops/ms
Iteration   3: 483.752 ops/ms
Iteration   4: 480.123 ops/ms
Iteration   5: 479.649 ops/ms
Iteration   6: 485.581 ops/ms
Iteration   7: 475.090 ops/ms
Iteration   8: 474.744 ops/ms
Iteration   9: 477.486 ops/ms
Iteration  10: 481.174 ops/ms

# Fork: 2 of 3
# Warmup Iteration   1: 473.716 ops/ms
# Warmup Iteration   2: 485.159 ops/ms
# Warmup Iteration   3: 488.145 ops/ms
# Warmup Iteration   4: 487.678 ops/ms
# Warmup Iteration   5: 486.726 ops/ms
# Warmup Iteration   6: 482.129 ops/ms
# Warmup Iteration   7: 492.143 ops/ms
# Warmup Iteration   8: 487.892 ops/ms
# Warmup Iteration   9: 490.247 ops/ms
# Warmup Iteration  10: 460.510 ops/ms
Iteration   1: 443.986 ops/ms
Iteration   2: 452.088 ops/ms
Iteration   3: 449.626 ops/ms
Iteration   4: 448.404 ops/ms
Iteration   5: 451.193 ops/ms
Iteration   6: 455.709 ops/ms
Iteration   7: 452.623 ops/ms
Iteration   8: 444.785 ops/ms
Iteration   9: 450.859 ops/ms
Iteration  10: 444.431 ops/ms

# Fork: 3 of 3
# Warmup Iteration   1: 466.004 ops/ms
# Warmup Iteration   2: 483.280 ops/ms
# Warmup Iteration   3: 486.830 ops/ms
# Warmup Iteration   4: 489.297 ops/ms
# Warmup Iteration   5: 489.369 ops/ms
# Warmup Iteration   6: 486.363 ops/ms
# Warmup Iteration   7: 487.051 ops/ms
# Warmup Iteration   8: 478.865 ops/ms
# Warmup Iteration   9: 486.185 ops/ms
# Warmup Iteration  10: 478.560 ops/ms
Iteration   1: 489.948 ops/ms
Iteration   2: 485.135 ops/ms
Iteration   3: 481.847 ops/ms
Iteration   4: 477.022 ops/ms
Iteration   5: 489.737 ops/ms
Iteration   6: 487.966 ops/ms
Iteration   7: 485.545 ops/ms
Iteration   8: 492.418 ops/ms
Iteration   9: 486.137 ops/ms
Iteration  10: 484.908 ops/ms
```

**Comment by carp84** [comment]
Thanks @klion26 , the deviation looks good, all less than 5%.
@pnowojski could you help review and decide whether this could be merged? Thanks.

**Review by pnowojski — APPROVED** [review]
Thanks for the fix :) I like the solution and detailed comments!

**Pull request merged**
