### PR TITLE
[FLINK-13846] Add benchmark of mapstate isEmpty

### PR DESCRIPTION
**Pull request by Myasuka**
Sine we have new API of `mapState#isEmpty()`, we should also have benchmarks on this.

### CODE REVIEW

**Comment by pnowojski** [comment]
As long as benchmark is stable LGTM % the test failure. Can you take a look at it @Myasuka ?

**Comment by Myasuka** [comment]
@pnowojski  This is due to we still use `1.9-SNAPSHOT` as flink version, I changed it to `1.10-SNAPSHOT` now.

**Comment by Myasuka** [comment]
@wsry , the CI failed due to `java.lang.OutOfMemoryError: Could not allocate enough memory segments for NetworkBufferPool` at [CI-report](https://travis-ci.org/dataArtisans/flink-benchmarks/builds/609160507?utm_source=github_status&utm_medium=notification) of `DataSkewStreamNetworkThroughputBenchmarkExecutor`, would you please take a look?

**Comment by pnowojski** [comment]
Upgrade from 1.9-SNAPSHOT to 1.10-SNAPSHOT has caused this failure? What has changed?

**Comment by Myasuka** [comment]
@wsry , as discussed offline previously, we just thought this was an occasional OOM, but my [private CI](https://travis-ci.org/Myasuka/flink-benchmarks/builds/610417111) also failed due to OOM. Please take a look at this problem.

**Comment by wsry** [comment]
I guess the reason is insufficient memory of the test environment. I will open a PR to fix the problem. @Myasuka @pnowojski

**Comment by wsry** [comment]
I found the test VM has more than 7G memory which should be enough. It is the ```exec-maven-plugin``` plugin which does not give enough memory to the test JVM process leading to the problem. Could you bother to fix the problem by adding a hotfix commit to avoid opening a new PR? @Myasuka

**Comment by pnowojski** [comment]
What's the status of this PR @wsry @Myasuka?

**Comment by wsry** [comment]
After discussed offline with @Myasuka , I open a new PR to fix the problem https://github.com/dataArtisans/flink-benchmarks/pull/35. Could you please take a look. @pnowojski

**Comment by pnowojski** [comment]
Thanks @wsry. Could you @Myasuka rebase on the master to let the travis check the PR?

**Comment by Myasuka** [comment]
Thanks the hot fix from @wsry , and already rebased with latest master branch @pnowojski .

**Review by pnowojski — APPROVED** [review]
LGTM

**Pull request merged**
