### PR TITLE
[FLINK-16460][benchmark] add Protobuf-based serialization benchmarks

### PR DESCRIPTION
**Pull request by NicoK**
This PR is based on #52 and adds further benchmarks to `SerializationFrameworkAllBenchmarks` that are based on using Protobuf via Kryo.

No special handling is needed; there are maven plugins that download OS-dependent Protobuf binaries that are used for the generation of the class files. At runtime, a Java library is used.

Examplary Benchmark run:
```
Benchmark                                 Mode  Cnt     Score    Error   Units
serializerAvro                           thrpt   30   661.345 ± 30.075  ops/ms
serializerAvroReflect                    thrpt   30   114.142 ±  3.542  ops/ms
serializerHeavyString                    thrpt   30   210.036 ±  2.734  ops/ms
serializerKryo                           thrpt   30   306.214 ± 14.382  ops/ms
serializerKryoProtobuf                   thrpt   30   913.351 ± 24.035  ops/ms
serializerKryoThrift                     thrpt   30   348.893 ± 16.150  ops/ms
serializerKryoThriftWithoutRegistration  thrpt   30   357.520 ± 13.993  ops/ms
serializerKryoWithoutRegistration        thrpt   30   205.663 ±  9.902  ops/ms
serializerPojo                           thrpt   30   880.954 ± 32.082  ops/ms
serializerPojoWithoutRegistration        thrpt   30   868.786 ± 30.351  ops/ms
serializerRow                            thrpt   30  1162.336 ± 29.574  ops/ms
serializerTuple                          thrpt   30  1297.177 ± 30.248  ops/ms
```

---
This change is [Reviewable](https://reviewable.io/reviews/dataartisans/flink-benchmarks/53)

### CODE REVIEW

**Review by pnowojski — COMMENTED** [review]
The same question as for #52 , could you post example results from the benchmark?

**Comment by NicoK** [comment]
I updated the description accordingly

**Review by pnowojski — APPROVED** [review]
LGTM

good to know, protobuf is the fastest.

**Comment by NicoK** [comment]
Not *the* fastest, but among them at least and the best Kryo serialization (`Row` and `Tuple` are faster)

**Comment by NicoK** [comment]
Revised performance benchmark: (300000 records per invocation, Flink 1.11 snapshot)
```
Benchmark                                  Mode  Cnt     Score    Error   Units
serializerAvro                             thrpt   30   635.093 ± 25.948  ops/ms
serializerAvroReflect                      thrpt   30   112.972 ±  3.300  ops/ms
serializerHeavyString                      thrpt   30   207.010 ±  3.065  ops/ms
serializerKryo                             thrpt   30   304.366 ± 12.129  ops/ms
serializerKryoProtobuf                     thrpt   30   821.096 ± 20.180  ops/ms
serializerKryoProtobufWithoutRegistration  thrpt   30   831.122 ± 20.881  ops/ms
serializerKryoThrift                       thrpt   30   566.158 ± 19.034  ops/ms
serializerKryoThriftWithoutRegistration    thrpt   30   546.198 ± 15.343  ops/ms
serializerKryoWithoutRegistration          thrpt   30   190.028 ±  6.912  ops/ms
serializerPojo                             thrpt   30   820.420 ± 19.132  ops/ms
serializerPojoWithoutRegistration          thrpt   30   809.189 ± 24.638  ops/ms
serializerRow                              thrpt   30  1066.995 ± 24.468  ops/ms
serializerTuple                            thrpt   30  1165.520 ± 27.922  ops/ms
```

Here as well, I would propose to remove the benchmark that adds additional registrations; this doesn't seem to be needed and is within the normal fluctuations of the benchmark.

**Review by pnowojski — APPROVED** [review]
LGTM

**Pull request merged**
