### PR TITLE
Run all benchmarks once on Travis CI

### PR DESCRIPTION
**Pull request by pnowojski**
This PR defines mvn test command and runs it on Travis CI

### CODE REVIEW

**Comment by pnowojski** [comment]
One problem here is that this uses flink version as specified in the pom.xml, while jenkins benchmark runs they use flink version from the flink/master branch. As long as we keep this `pom.xml` up to date, they will be running the same code.

**Review by carp84 — APPROVED** [review]
+1, LGTM. Thanks.

**Comment by NicoK** [comment]
@pnowojski can you share a rational as to why to add this? Is it a form of testing whether the benchmarks run / to verify PRs? In that case, it does not really matter anyway whether the executed version is different or not.

**Comment by pnowojski** [comment]
Yes, it's for a verification purpose. Unfortunately @NicoK it matters, take a look at this issue https://github.com/dataArtisans/flink-benchmarks/pull/16 . Change in Flink repository caused network benchmarks to fail because of some dependency issues. Also someone can brake the compatibility in the classes that `flink-benchmarks` are using.

**Comment by NicoK** [comment]
But then simply adding Travis runs after commits to `flink-benchmarks` wouldn't help (for this #16). You'd need daily travis runs like in Flink and notify someone of this failure. Also, you could get the latest revision of the Flink repo and run it just like in our test environment.

**Comment by pnowojski** [comment]
I think I configured somewhere that travis build will be scheduled once couple of days or once a day if it was inactive. True, we could use of some notifications. I wasn't claiming that this PR will solve all the problems and bring peace to the world :) It cheaply makes things a bit better.

**Pull request merged**
